server:
  port: 8082

spring:
  application:
    name: sales-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: salesdb
      username: admin
      password: admin
      authentication-database: admin